name: Build Installers
on:
  workflow_dispatch:
    inputs:
      version:
        description: "App version"
        required: true
        default: "0.1.0"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install

      - name: Build Renderer & Main
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    
        run: npm run build
        

      - name: Package for macOS
        if: matrix.os == 'macos-latest'
        run: |
          npx electron-builder \
            --mac \
            --publish never \
            --config.mac.minimumSystemVersion=10.13.6 \
            --x64

      - name: Package for Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --publish never

      - name: Package for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npx electron-builder --linux --publish never

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os == 'macos-latest' && 'installers_high_sierra_mac' || format('installers_{0}', matrix.os) }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.zip
            !dist/*-unpacked/
            !dist/*.blockmap
          retention-days: 5